name: devcontainer
description: Run in devcontainer
inputs:
  dc-user:
    description: Who run the commands
    default: root
  action:
    description: Action to be run
    required: true
  make:
    description: Make target to run
outputs:
  container:
    description: "Container name"
    value: ${{ steps.run.outputs.container }}
runs:
  using: composite
  steps:
    - id: run
      run: |
        . ${{ github.action_path }}/jh-github-dc ${{ inputs.action }} ${{ inputs.make }}
        echo "::set-output name=random-number::${CONTAINER_NAME}"
      shell: bash
      env:
        DC_USER: ${{ inputs.dc-user }}
    
    - name: Upload artifacts docker's logs
      if: ${{ inputs.action == 'stop' }}
      uses: actions/upload-artifact@v3
      with:
        name: docker
        path: tmp/docker.log
        if-no-files-found: ignore
