name: devcontainer
description: Run in devcontainer
inputs:
  action:
    description: Action to be run
    default: run
  run:
    description: Shell to run
  dc-user:
    description: Who run the commands (root)
  privileged:
    description: Should we run with the privileged flag? (false)
  init:
    description: Should we run with the init flag? (false)
  with-socket:
    description: (future) Do we mount the docker socket inside? (false)
outputs:
  container:
    description: "Container name"
    value: ${{ steps.run.outputs.container }}
runs:
  using: "node16"
  main: "main.js"
  post: "cleanup.js"