name: devcontainer
description: Run in devcontainer
inputs:
  dc-user:
    description: Who run the commands
    default: root
  action:
    description: Action to be run
    required: true
  make:
    description: Make target to run
  dc-arg-0:
    description: Additionnal arguments to the docker command
  dc-arg-1:
    description: Additionnal arguments to the docker command
  dc-env-0:
    description: Additionnal environment [0] to the docker command
  dc-env-1:
    description: Additionnal environment [1] to the docker command
  dc-env-2:
    description: Additionnal environment [2] to the docker command
  dc-env-3:
    description: Additionnal environment [3] to the docker command
outputs:
  container:
    description: "Container name"
    value: ${{ steps.run.outputs.container }}
runs:
  using: composite
  steps:
    - id: run
      run: |
        . ${{ github.action_path }}/jh-github-dc ${{ inputs.action }} ${{ inputs.make }}
        echo "::set-output name=container::${CONTAINER_NAME}"
      shell: bash
      env:
        DC_USER: ${{ inputs.dc-user }}
        DC_ARG_0: ${{ inputs.dc-arg-0 }}
        DC_ARG_1: ${{ inputs.dc-arg-1 }}
        DC_ENV_0: ${{ inputs.dc-env-0 }}
        DC_ENV_1: ${{ inputs.dc-env-1 }}
        DC_ENV_2: ${{ inputs.dc-env-2 }}
        DC_ENV_3: ${{ inputs.dc-env-3 }}
        DC_TMP: tmp/dc
    
    - name: Upload dc log
      if: ${{ inputs.action == 'stop' }}
      uses: actions/upload-artifact@v3
      with:
        name: dc-logs
        path: tmp/dc
        if-no-files-found: ignore
