name: devcontainer
description: Run in devcontainer
inputs:
  action:
    description: Action to be run
    default: run
  run:
    description: Shell to run
  dc-user:
    description: Who run the commands
    default: root
outputs:
  container:
    description: "Container name"
    value: ${{ steps.run.outputs.container }}
runs:
  using: composite
  steps:
    - id: run
      run: |
        . ${{ github.action_path }}/jh-github-dc "${{ inputs.action }}" "${{ inputs.run }}"
        echo "container='${CONTAINER_NAME}'" > "$GITHUB_OUTPUT"
      shell: bash
      env:
        DC_TMP: tmp/dc
        PARAM_USER: ${{ inputs.dc-user }}
    
    - name: Upload dc log
      if: ${{ inputs.action == 'stop' }}
      uses: actions/upload-artifact@v3
      with:
        name: dc-logs
        path: tmp/dc
        if-no-files-found: ignore
