name: devcontainer
description: Run in devcontainer
inputs:
  dc-user:
    description: Who run the commands
    default: root
  action:
    description: Action to be run
    required: true
  make:
    description: Make target to run
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/jh-github-dc ${{ inputs.action }} ${{ inputs.make }}
      shell: bash
      env:
        DC_USER: ${{ inputs.dc-user }}

    #   run: echo "::set-output name=random-number::$(echo $RANDOM)"
    
    - name: Upload artifacts docker's logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: docker
        path: tmp/docker.log
        retention-days: 1