#!/usr/bin/env bash

set -o errexit

#
# Documentation:
#  - Default env variables: https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
#  - Pseudo commands:       https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
#

PRJ_NAME="$(basename "$GITHUB_REPOSITORY")"
TAG_NAME="local"
CONTAINER_NAME="devcontainer"
DC_USER="${DC_USER:-root}"
DOCKER_CONTEXT=".devcontainer/"
DOCKER_STARTUP_DELAY=60

CMD="$1"
CMD_ARG="$2"

header_begin() {
    echo "$1..."
}

header_end() {
    echo "...done"
}

case "$CMD" in
"dump")
    echo "******************************"
    echo "* _0:                $0"
    echo "* PRJ_NAME:          $PRJ_NAME"
    echo "* CONTAINER_NAME:    $CONTAINER_NAME"
    echo "* TAG_NAME:          $TAG_NAME"
    echo "* DC_USER:           $DC_USER"
    echo "* GITHUB_WORKSPACE:  $GITHUB_WORKSPACE"
    echo "* GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
    echo "* "
    echo "* CMD [1]:           $CMD"
    echo "* CMD_ARG [2]:       $CMD_ARG"
    echo "******************************"
    ;;

"start")
    header_begin "Building the docker image '$TAG_NAME'"
    docker build -t "$TAG_NAME" "$DOCKER_CONTEXT"
    header_end

    header_begin "Starting in the docker '$CONTAINER_NAME' from '$TAG_NAME'"
    mkdir tmp/
    docker run --name "$CONTAINER_NAME" --privileged --volume "$PWD:/workspaces/$PRJ_NAME" --workdir "/workspaces/$PRJ_NAME" "$TAG_NAME" sleep infinity >tmp/docker.log 2>&1
    header_end

    header_begin "Wait for docker to be ready"
    ((I = 1)) # If it was 0, it would fail the script
    ((MAX = "$DOCKER_STARTUP_DELAY"))
    while ! docker ps --filter "name=$CONTAINER_NAME" --filter "status=running" | grep "$CONTAINER_NAME" >/dev/null; do
        sleep 1s
        echo -n "."
        ((I++))
        ((I > MAX)) && (
            echo "Waited $I and $CONTAINER_NAME times without success" >&2
            exit 2
        )
    done
    header_end
    ;;

"stop")
    docker kill "$CONTAINER_NAME"
    ;;

"make")
    header_begin "Make $CMD"
    docker exec --user "$DC_USER" "$CONTAINER_NAME" make "$CMD_ARG"
    header_end
    ;;

*)
    echo "Unknown command: $CMD" >&2
    exit 1
    ;;

esac
